services:
  db:
    image: postgres:15-alpine
    container_name: auth_test_db
    hostname: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    container_name: auth_test_app
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && 
             pytest --alluredir=allure-results"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: